#!/usr/bin/env python2
import sys, os

# Make imports work without PYTHONPATH
sys.path.append(
  os.path.dirname(              # Mailpile root
    os.path.dirname(              # scripts/
      os.path.realpath(__file__)))) # this script

from mailpile.app import Main

Main(sys.argv[1:])
