#!/usr/bin/env python
import sys, os

# add root to sys.path so imports work without PYTHONPATH
sys.path.append(os.path.dirname(__file__))

from mailpile.app import Main

# Load the standard plugins
from mailpile.plugins import *

Main(sys.argv[1:])
