#!/usr/bin/env python2.7
import sys, os

# Make imports work without PYTHONPATH
mailpile_root = os.path.dirname(     # Mailpile root
    os.path.dirname(                 # scripts/
        os.path.realpath(__file__))) # this script

sys.path = [mailpile_root, os.path.join(mailpile_root, 'lib')] + sys.path

from mailpile.app import Main
Main(sys.argv[1:])
