/* Setup - Complete - Model */
Mailpile.silly_strings = {
  copying: [
    '{{_("Mail is being imported into your Mailpile")|escapejs}}',
    '{{_("Copying your mail, please do not be alarmed!")|escapejs}}',
    '{{_("Copying mail. This could take a while")|escapejs}}',
    '{{_("Please be patient, we are copying mail as fast as possible")|escapejs}}',
    '{{_("Wow, you have a lot of mail")|escapejs}}',
    '{{_("I hope you dont have a plane to catch or anything")|escapejs}}',
    '{{_("Copying mail. Put your arms above your head and whistle La Cucaracha")|escapejs}}',
    '{{_("Making a copy of your mail. Putting it in your inbox, all comfy like")|escapejs}}'
  ],
  nerds: [
    '{{_("Damn kids.")|escapejs}}',
    '{{_("RMS approves!")|escapejs}}',
    '{{_("Formatting your C:\\ drive... (just kidding)")|escapejs}}',
    '{{_("Fortifying encryption shields")|escapejs}}',
    '{{_("Increasing entropy & scrambling bits")|escapejs}}',
    '{{_("Patching bugs...")|escapejs}}',
    '{{_("Indexing kittens...")|escapejs}}',
    '{{_("Indexing lovenotes")|escapejs}}',
    '{{_("Reticulating Splines")|escapejs}}',
    '{{_("Syntax error in line 45 of this e-mail")|escapejs}}',
    '{{_("Shoveling more coal into the server")|escapejs}}',
    '{{_("Calibrating flux capacitors")|escapejs}}',
    '{{_("A few bytes tried to escape, but we caught them")|escapejs}}',
    '{{_("Deterministically simulating future state")|escapejs}}',
    '{{_("Embiggening prototypes")|escapejs}}',
    '{{_("Resolving interdependence")|escapejs}}',
    '{{_("Spinning violently around the y-axis")|escapejs}}',
    '{{_("Locating additional gigapixels")|escapejs}}',
    '{{_("Initializing hamsters")|escapejs}}',
    '{{_("This is our world now... the world of the electron and the switch")|escapejs}}',
    '{{_("Fedexing all your spam to online advertisers...")|escapejs}}',
    '{{_("Becoming self-aware")|escapejs}}',
    '{{_("Looking for heretofore unknown prime numbers")|escapejs}}',
    '{{_("Re-aligning satellite grid")|escapejs}}',
    '{{_("Re-routing bitstream")|escapejs}}',
    '{{_("Warming up particle accelerator")|escapejs}}',
    '{{_("Time is an illusion. Loading time doubly so")|escapejs}}',
    '{{_("Verifying local gravitational constant")|escapejs}}',
    '{{_("This server is powered by a lemon and two electrodes")|escapejs}}'
  ],
  email: [
    '{{_("Wow, you have a lot of mail")|escapejs}}',
    '{{_("Mailpile has an advanced tagging system & search engine at its core")|escapejs}}',
    '{{_("Do you really need to keep all these Amazon Prime shipping confirmations?")|escapejs}}',
    '{{_("I am pretty sure e-mail from ThinkGeeks 2011 X-mas sale can be deleted.")|escapejs}}',
    '{{_("Do you really need an e-mail to know when you have been retweeted?")|escapejs}}',
    '{{_("E-mail is the largest internet based social network on the planet")|escapejs}}',
    '{{_("Which other technology do you use that is 40 years old?")|escapejs}}',
    '{{_("There are 2.5 billion e-mail users worldwide, that is double the amount of Facebook users!")|escapejs}}',
    '{{_("Use Mailpile Tags to better organize and search your mail")|escapejs}}',
    '{{_("Remember getting your first e-mail address? Remember how it felt like something private?")|escapejs}}',
    '{{_("E-mail is decentralized by design, this means no one company or government owns it!")|escapejs}}',
    '{{_("Over 100 trillion e-mails are sent per year, wow!")|escapejs}}',
    '{{_("E-mail is the most widely used communication protocol ever created by humans")|escapejs}}',
    '{{_("E-mail uses an open standard agreed upon by the entire world & owned by no one")|escapejs}}'
  ],
  security: [
    '{{_("BCC-ing ALL THE SPIES!")|escapejs}}',
    '{{_("Many powerful governments are conducting mass dragnet surveillance")|escapejs}}',
    '{{_("Most e-mail can be read by network operators as it travels through the internet")|escapejs}}',
    '{{_("Encryption ensures that your e-mails are only read by the intended recipient")|escapejs}}',
    '{{_("Unencrypted e-mail is more like sending a postcard than sending a letter")|escapejs}}',
    '{{_("Mailpile uses OpenPGP to encrypt and decrypt your messages securely")|escapejs}}',
    '{{_("All of your config settings & passwords are encrypted with AES-256")|escapejs}}',
    '{{_("Encrypting e-mails means your communication actually stays private")|escapejs}}',
    '{{_("The more encrypted e-mail you send, the better!")|escapejs}}',
    '{{_("Make sure you print or save your keys & passwords somewhere secure")|escapejs}}',
    '{{_("Mailpile by default encrypts your search index!")|escapejs}}',
    '{{_("The most common e-mail password is 123456, hopefully yours is different")|escapejs}}'
  ],
  misc: [
    '{{_("Good things come to those who wait")|escapejs}}',
    '{{_("Make Free Software and be happy")|escapejs}}',
    '{{_("Much of Mailpile was built in cafes in Reykjavík, Iceland")|escapejs}}',
    '{{_("Many Icelanders believe in elves and magical hidden people")|escapejs}}',
    '{{_("The founders of Mailpile first met in a public hot tub in Reykjavík")|escapejs}}',
    '{{_("We like volcanos, do you like volcanos?")|escapejs}}',
    '{{_("A million hamsters are spinning their wheels right now")|escapejs}}',
    '{{_("Tapping earth for more geothermal energy")|escapejs}}',
    '{{_("Digging moat. Filling with alligators. Fortifying walls")|escapejs}}',
    '{{_("Crossing out swear words...")|escapejs}}',
    '{{_("Compiling bullshit bingo grid...")|escapejs}}',
    '{{_("Abandon all hope, ye who enter here")|escapejs}}',
    '{{_("Welcome to the nine circles of suffering")|escapejs}}',
    '{{_("Informing David Cameron of suspicious ac^H^H^H ... naaah :)")|escapejs}}',
    '{{_("Letting you wait for no apparent reason")|escapejs}}',
    '{{_("What are you wearing?")|escapejs}}',
    '{{_("Go put the kettle on, this could be a while")|escapejs}}',
    '{{_("Go get a cup of tea and some biscuits. This will take approximately 4 custard creams worth of time")|escapejs}}',
    '{{_("Did you know humans share 50 percent of their DNA with a banana? Freaky")|escapejs}}',
    '{{_("Estimating chance of astroid hitting Earth")|escapejs}}',
    '{{_("Reading Terms of Service documents")|escapejs}}',
    '{{_("Catching up on shows on Netflix")|escapejs}}',
    '{{_("Oh, you have some very interesting old e-mails")|escapejs}}',
    '{{_("I think I better understand you now")|escapejs}}',
    '{{_("Your past is just a story you tell yourself")|escapejs}}',
    '{{_("Checking e-mails for stolen Winklevoss ideas")|escapejs}}',
    '{{_("Applying coupons...")|escapejs}}',
    '{{_("Licking stamps...")|escapejs}}',
    '{{_("Self potato")|escapejs}}',
    '{{_("Yum yum, that one was tasty")|escapejs}}',
    '{{_("Hey, there is some Nigerian prince here who wants to give you twenty million dollars...")|escapejs}}',
    '{{_("How rude!")|escapejs}}',
    '{{_("Now enhancing photos")|escapejs}}',
    '{{_("Backing up the entire Internet...")|escapejs}}',
    '{{_("Really? You are still waiting?")|escapejs}}',
    '{{_("Well... it sure is a beautiful day")|escapejs}}',
    '{{_("You should probably go outside or something")|escapejs}}',
    '{{_("Slacking off over here")|escapejs}}',
    '{{_("Doing nothing")|escapejs}}',
    '{{_("Making you wait for no reason")|escapejs}}',
    '{{_("Testing your patience")|escapejs}}',
    '{{_("Pay no attention to the man behind the curtain")|escapejs}}',
    '{{_("You are great just the way you are")|escapejs}}',
    '{{_("Warning: do not think of purple hippos")|escapejs}}',
    '{{_("Follow the white rabbit")|escapejs}}',
    '{{_("Wanna see how deep the rabbit hole goes?")|escapejs}}',
    '{{_("Supplying monkeys with typewriters")|escapejs}}',
    '{{_("Waiting for Godot.")|escapejs}}',
    '{{_("Swapping time and space")|escapejs}}'
  ]
};

